// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIRc_4IYYeh6jqRFD7hBzuBr1AgS9Ig3k',
    appId: '1:735274580659:web:d812598a7b77001052cec6',
    messagingSenderId: '735274580659',
    projectId: 'app-memories-jcj',
    authDomain: 'app-memories-jcj.firebaseapp.com',
    storageBucket: 'app-memories-jcj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASwp6nmN45e9FjjL772CenVQVDDN6Q_eU',
    appId: '1:735274580659:android:d30bf2d99e48569752cec6',
    messagingSenderId: '735274580659',
    projectId: 'app-memories-jcj',
    storageBucket: 'app-memories-jcj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5hjpQoHpNCIZpFcvFG_wmwRaoZj06jOk',
    appId: '1:735274580659:ios:6d23f0974a5a4c6b52cec6',
    messagingSenderId: '735274580659',
    projectId: 'app-memories-jcj',
    storageBucket: 'app-memories-jcj.appspot.com',
    iosClientId: '735274580659-qetpvprvin9auhrosfn20s11mape41al.apps.googleusercontent.com',
    iosBundleId: 'com.example.appMemories',
  );
}
